package com.bank.bian.customertaxwithholding;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Customer Tax Withholding
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Account Management
 * Functional Pattern: Process
 * Asset Type:         Tax Withholding Record
 * Control Record:     Tax Withholding Record Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Customer Tax Withholding — BIAN Semantic API")
                .description("Service Domain 'Customer Tax Withholding' (Process pattern) "
                        + "operating on the 'Tax Withholding Record Procedure' control record.")
                .version("0.1.0"));
    }
}
